# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# Used variables in this file can be found with:
# grep -r "\\\$" _config.template.yml \
#     | sed -e 's|[$]|\n#|g' \
#     | grep -e '^\#{' \
#     | sed -e 's|[^$]*[$]|\n#|g' -e 's|}.*||' -e 's|^#{||' \
#     | sort -u

title: ASK-Training ${type} - ${title}
email: ${email}
description: >- # this means to ignore newlines until "baseurl:"
  ASK-Training  ${type} test site. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/${gh_repo_name}" # the subpath of your site, e.g. /blog
url: "https://${gh_org_name}.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repo_browse_url: "https://github.com/${gh_org_name}/${gh_repo_name}/"
repo_raw_url: "https://raw.githubusercontent.com/${gh_org_name}/${gh_repo_name}/"
git_ref: "${branch}"

# Build settings
theme: minima
plugins:
    - jekyll-rdf

jekyll_rdf:
  baseiri: "${base_iri}/"
  path: "_data/${type}.ttl"
  default_template: "default.html"
  class_template_mappings:
    "${base_iri}/Training": "training.html"
    "${base_iri}/Module": "module.html"
    "${base_iri}/Resource": "resource.html"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
